spring:
  datasource:
    url: ENC(pqKr01+9m90wJTW4kf/ZwWHv/U9UVcqeqOdF4T6ppvB+lAKkY1ry1oIcJStA+Y/x)
    username: ENC(+Vltkl7cvDg71qVXEyMoCw==)
    password: ENC(wMHs50BVfRUCxCNHm3T03EfO9pcycbx0)

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

springdoc:
  api-docs:
    path: /api-docs